### PR TITLE
fix: ensure that the post request is successful

### LINKED ISSUE #95: Server Error
**Describe the bug**
I didn’t expect this problem to be caused by windicss, and it took me to investigate for a long time. :(

**Minimal Reproductions**
- clone https://github.com/anncwb/server-bug
- yarn && yarn dev
- start server 
- cd ./server.  && yarn start
- Open the browser and find that Vite’s post proxy cannot be sent out

I checked many places, but I didn't expect it to be a problem with this plugin. Back to 0.8.4 the problem disappeared

**Versions**
- vite-plugin-windicss:0.9.2
- vite:2.0.5
- framework(vue/react/svelte/etc):vue

**Additonal Context**

### PR DESCRIPTION
**Pull request by anncwb**
Fix #95

When body-parser is used globally, Vite proxy post request will be invalid. So the body-parser plug-in is removed, and the parameters in the body are obtained manually

### CODE REVIEW

**Comment by antfu** [comment]
Thanks a lot! I was trouble finding a way to handle the body.

You can remove the comments in the code, so as the `yarn.lock` (use `pnpm` here). I can update the lock later.

File: packages/vite-plugin-windicss/src/devtools.ts [hunk 1]
```diff
@@ -111,3 +111,23 @@ document.head.prepend(style)
       },
     }]
 }
+
+
+function getBodyJson(req: any): Record<string, any> {
+  return new Promise((resolve) => {
+    let body = '';
+    let jsonStr = '';
```
Comment (antfu) [inline packages/vite-plugin-windicss/src/devtools.ts:119]:
```suggestion
    let json = {}
```

**Comment by anncwb** [comment]
Please wait, I submitted a useless document. I delete

**Comment by anncwb** [comment]
@antfu I re-posted it, and is it possible to add options to configure whether devtools is enabled or not. If you have this option, you can also choose to close devtools to solve this problem

**Comment by antfu** [comment]
Sure we can have an option for it but I was thinking to minimize the interface that the user would need to configure to enable the feature. I think with your fix, the global population should be gone and we are good now. Thank you!
